### ISSUE TITLE
bullet: 401 Unauthorized

### ISSUE THREAD

**Issue by eccyan** [mitsuse/bullet#2]
Hi, I want gun the bullet with your library.
But I cannot gun bulets becouse Unauthorized error occued.

My System is CentOS release 6.5 (Final) on Vagrant.
I installed with `go get -u github.com/mitsuse/bullet`, and `export BULLET_ACCESS_TOKEN=MY_TOKEN` wrote in `~/.bash_profile`

Do I need some other settings ?

Anyway, Thanks !

**Comment by eccyan** [comment]
Ok, I can gun the bullet as follows.
`
BULLET_ACCESS_TOKEN=MY_TOKEN bullet send -l http://example.com
`
Is this golang environmental problem?

**Comment by mitsuse** [comment]
@eccyan Sorry for my late reply.

I have two questions:
- What version of go did you use to compile bullet?
- Was `~/.bash_profile` correctly loaded when auth failed? The Failure may be caused because the old access token (just old or wrong) is loaded.

Thanks!
